meta_product_name: "Somani"
meta_title: "Somani - Immerse yourself in Japanese"
meta_description: "Learn Japanese through daily adventures, saved words, and JLPT practice."
meta_image: "cover.png"
twitter_account: ""
